flaskproject/routes.py
# import json
import logging
from datetime import datetime, timedelta
from functools import wraps

from flask import (
    Blueprint,
    abort,
    json,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user
from flaskproject import db, login, utils
from flaskproject.models import (
    Category,
    Product,
    Receipt,
    ReceiptDetail,
    User,
    UserRole,
)
from sqlalchemy import func, or_
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func
from sqlalchemy.sql.functions import coalesce

bp = Blueprint("main", __name__)


@bp.context_processor
def common_response():
    return {"cart_stats": utils.count_cart(session.get("cart"))}


def admin_required(f):
    """
    Decorator tùy chỉnh để đảm bảo người dùng là ADMIN.
    Phải được đặt SAU @login_required.
    """

    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.userrole != UserRole.ADMIN:
            abort(403)
        return f(*args, **kwargs)

    return decorated_function


@bp.route("/")
def home():
    css_file = [
        "css/style.css",
        "css/topnav.css",
        "css/header.css",
        "css/banner.css",
        "css/taikhoan.css",
        "css/trangchu.css",
        "css/home_products.css",
        "css/pagination_phantrang.css",
        "css/footer.css",
    ]
    cate_id = request.args.get("category_id", type=int)
    cates = utils.load_categories()
    kw = request.args.get("keyword")
    from_price = request.args.get("from_price")
    to_price = request.args.get("to_price")
    page = request.args.get("page", 1, type=int)
    price_range = request.args.get("price_range")
    sort_key = request.args.get("sort")

    if price_range:
        try:
            parts = price_range.split("-")
            if len(parts) == 2:
                from_price = parts[0]
                to_price = parts[1]
        except Exception as e:
            print(f"Error parsing price_range: {e}")

    pagination = utils.load_products(
        cate_id=cate_id,
        kw=kw,
        from_price=from_price,
        to_price=to_price,
        page=page,
        sort_key=sort_key,
    )
    products = pagination.items
    if "HX-Request" in request.headers:
        return render_template(
            "partials/_htmx_response.html",
            products=products,
            pagination=pagination,
            categories=cates,
            current_category_id=cate_id,
        )
    return render_template(
        "blog/index.html",
        title="Thế giới di động",
        css_file=css_file,
        categories=cates,
        products=products,
        pagination=pagination,
        current_category_id=cate_id,
    )


@bp.route("/login", methods=["GET", "POST"])
def user_login():
    err_msg = ""
    if request.method.__eq__("POST"):
        username = request.form.get("username")
        password = request.form.get("password")

        user = utils.check_login(username=username, password=password)
        if user:
            login_user(user=user)
            print(
                f"DEBUG: Đăng nhập thành công! User: {user.username}, Vai trò: {user.userrole}"
            )
            # Kiểm tra vào trò khi login
            if user.userrole == UserRole.ADMIN:
                return redirect(url_for("main.admin"))

            next = request.args.get("next", "main.home")
            return redirect(url_for(next))
        else:
            err_msg = "Username hoặc Password không chính xác!"
    return render_template("auth/login.html", err_msg=err_msg)


@bp.route("/user-logout")
def user_signout():
    logout_user()
    return redirect(url_for("main.home"))


@login.user_loader
def user_load(user_id):
    return utils.get_user_by_id(user_id=user_id)


@bp.route("/register", methods=["GET", "POST"])
def register():
    err_msg = ""
    if request.method.__eq__("POST"):
        name = request.form.get("name")
        username = request.form.get("username")
        email = request.form.get("email")
        password = request.form.get("password")
        confirm = request.form.get("confirm")
        try:
            if password.strip().__eq__(confirm.strip()):
                utils.add_user(
                    name=name, username=username, email=email, password=password
                )
                return redirect(url_for("main.home"))
            else:
                err_msg = "Mật khẩu không khớp!!!"
        except Exception as e:
            err_msg = "Hệ thống có lỗi" + str(e)

    return render_template("auth/register.html", err_msg=err_msg)


@bp.route("/cart")
def cart():
    return render_template(
        "blog/cart.html", stats=utils.count_cart(session.get("cart", {}))
    )


@bp.route("/api/add-cart", methods=["POST"])
def add_to_cart():
    data = request.json
    id = str(data.get("id"))
    name = data.get("name")
    price = float(data.get("price"))
    img = data.get("img")
    quantity = int(data.get("quantity"))

    cart = session.get("cart")
    if not cart:
        cart = {}

    if id in cart:

        cart[id]["quantity"] = cart[id]["quantity"] + quantity
    else:

        cart[id] = {
            "id": id,
            "name": name,
            "price": price,
            "quantity": quantity,
            "img": img,
        }

    session["cart"] = cart

    return jsonify(utils.count_cart(cart=cart))


@bp.route("/api/remove-cart", methods=["POST"])
def remove_from_cart():
    try:
        data = request.json
        id_to_remove = str(data.get("id"))

        cart = session.get("cart")
        if cart and id_to_remove in cart:
            cart.pop(id_to_remove, None)
            session["cart"] = cart
            return (
                jsonify(
                    {
                        "code": 200,
                        "message": "Xóa thành công",
                        "stats": utils.count_cart(cart),
                    }
                ),
                200,
            )
        else:
            return (
                jsonify({"code": 404, "error": "Sản phẩm không tìm thấy trong giỏ"}),
                404,
            )

    except Exception as e:
        print(f"Lỗi khi xóa giỏ hàng: {e}")
        return jsonify({"code": 500, "error": "Lỗi máy chủ nội bộ"}), 500


@bp.route("/pay")
@login_required
def methods_pay():
    product_id = request.args.get("product_id", type=int)

    if product_id:
        product = Product.query.get(product_id)

        if product:
            cart_data = {
                str(product.id): {
                    "id": str(product.id),
                    "name": product.name,
                    "price": product.price,
                    "quantity": 1,
                    "img": product.image,
                }
            }
            session["cart"] = cart_data
            session.modified = True
        else:
            session["cart"] = {}
            session.modified = True
    cart_data = session.get("cart", {})
    return render_template("blog/pay.html", cart_items=cart_data)


@bp.route("/process-order", methods=["POST"])
@login_required
def process_order():
    # data = request.get_json()
    cart = session.get("cart", {})

    if not cart:
        return jsonify({"success": False, "error": "Giỏ hàng của bạn trống."}), 400

    try:
        data = request.get_json() or {}
        current_user_id = current_user.id
        utils.add_receipt(
            cart_from_session=cart, user_id=current_user_id, shipping_info=data
        )
        # Xóa giỏ hàng sau khi lưu thành công
        session["cart"] = {}
        session.modified = True

        return jsonify(
            {
                "success": True,
                "fullName": data.get("fullName"),
                "phone": data.get("phone"),
            }
        )
    except Exception as e:
        logging.error(f"LỖI khi xử lý đơn hàng: {e}")
        return (
            jsonify({"success": False, "error": f"Không thể xử lý đơn hàng: {str(e)}"}),
            500,
        )


@bp.route("/product/<int:product_id>")
def products_details(product_id):
    product = Product.query.get_or_404(product_id)
    flash_price = utils.get_current_flash_sale_price(product_id)

    if flash_price is not None:

        product.old_price = product.price

        product.price = flash_price
    return render_template("blog/products_details.html", product=product)


@bp.route("/api/get-flash-sale")
def get_flash_sale():
    cache_file_path = "flash_sale_cache.json"
    now = datetime.now()
    sale_duration_hours = 3

    try:
        with open(cache_file_path, "r") as f:
            cache = json.load(f)
        sale_start_time = datetime.fromisoformat(cache["start_time"])
    except FileNotFoundError:
        cache = {}
        sale_start_time = now - timedelta(days=1)

    if now > sale_start_time + timedelta(hours=sale_duration_hours):

        new_products_list = utils.get_new_flash_sale_data(count=5)

        if new_products_list:
            sale_start_time = now
            cache = {
                "products": new_products_list,
                "start_time": sale_start_time.isoformat(),
            }

            with open(cache_file_path, "w") as f:
                json.dump(cache, f, indent=4)
        else:
            return jsonify({"error": "No active flash sale products"}), 404

    sale_end_time = sale_start_time + timedelta(hours=sale_duration_hours)

    return jsonify(
        {
            "products": cache.get("products", []),
            "sale_end_time": sale_end_time.isoformat(),
        }
    )


@bp.route("/admin")
@login_required
@admin_required
def admin():
    return render_template("admin/admin_panel.html")


@bp.route("/api/admin/dashboard_stats")
@login_required
def get_dashboard_stats():
    """
    API cung cấp số liệu thống kê bằng cách truy vấn database.
    """
    try:

flaskproject/templates/partials/_htmx_response.html
{% include 'partials/_product_list.html' %}

<div id="category-nav-wrapper" hx-swap-oob="true">
    {% include 'partials/_nav.html' %}
</div>

flaskproject/templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light category-nav" id="all-products-section">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item {% if not current_category_id %} active {% endif %}">
                    <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}"
                        hx-get="{{ url_for('main.home') }}"
                        hx-target="#product-list"
                        hx-swap="innerHTML"
                        hx-push-url="true">
                        All
                    </a>
                </li>
            {% for c in categories %}
                <li class="nav-item {% if c.id == current_category_id %} active {% endif %}">
                    <a class="nav-link" href="{{ url_for('main.home', category_id=c.id) }}"
                        hx-get="{{ url_for('main.home', category_id=c.id) }}"
                        hx-target="#product-list"
                        hx-swap="innerHTML"
                        hx-push-url="true">
                        {{ c.name }}
                    </a>
                </li>
            {% endfor %}
            </ul>
      
        </div>
    </div>
</nav>

flaskproject/templates/partials/_product_list.html
<div class="product-title" style="padding: 20px 100px;">
    <h5><i class="fa-solid fa-fire icon-fire"></i>Tất cả sản phẩm</h5>
</div>

{% if products %}
<div class="row align-items-stretch" style="padding: 0px 100px;">
  {% for p in products %}
  <div class="col-md-3 col-6" style="padding: 5px">
    <div class="card h-100 d-flex flex-column" style="padding: 5px">
      <a href="{{ url_for('main.products_details', product_id=p.id) }}">
        {% if p.image %}
        <img
          src="{{ url_for('static', filename=p.image) }}"
          class="card-img-top"
          alt="{{ p.name }}"
          style="object-fit: contain; height: 150px"
        />
        {% else %}
        <img
          src="{{ url_for('static', filename='img/default.png') }}"
          class="card-img-top"
          alt="Ảnh mặc định"
          style="object-fit: contain; height: 150px"
        />
        {% endif %}
      </a>

      <div class="card-body d-flex flex-column">
        <a
          href="{{ url_for('main.products_details', product_id=p.id) }}"
          class="product-link-wrapper"
        >
          <h7 class="card-title" style="color: #1d2939; line-height: 21px">
            {{ p.name }}
          </h7>
          <div class="card-text" style="font-size: smaller">
            <span class="spec-tag">{{ p.screen }}</span>
            <span class="spec-tag" style="margin-top: 5px">
              SSD {{ p.store }}
            </span>
          </div>

          <strong
            class="card-text"
            style="color: #dd2f2c; font-weight: bold; font-size: 18px"
          >
            {{ "{:,.0f}".format(p.price).replace(",", ".") }}₫
          </strong>

          <div class="product-rating" style="font-size: smaller">
            {% if p.rating_score and p.rating_score > 0 %}
            <i class="fa-solid fa-star"></i>
            <span class="rating-score">
              {{ "%.1f"|format(p.rating_score) }}
            </span>
            {% endif %} {% if p.sold_count and p.sold_count > 0 %} {% if
            p.rating_score and p.rating_score > 0 %}
            <span class="bullet">•</span>
            {% endif %}
            <span class="sold-count">
              Đã bán {% if p.sold_count >= 1000 %} {{
              ("%.1f"|format(p.sold_count / 1000)).replace('.', ',') }}k {% else
              %} {{ p.sold_count }} {% endif %}
            </span>
            {% endif %}
          </div>
        </a>
        <div class="button-container mt-auto">
          <button
            type="button"
            class="my-Btn"
            onclick="addToCart(event, {{ p.id }}, '{{ p.name}}', {{ p.price }}, '{{ url_for('static', filename=p.image) }}')"
          >
            <div class="sign">
              <svg viewBox="0 0 576 512">
                <path
                  d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96zM252 160c0 11 9 20 20 20h44v44c0 11 9 20 20 20s20-9 20-20V180h44c11 0 20-9 20-20s-9-20-20-20H356V96c0-11-9-20-20-20s-20 9-20 20v44H272c-11 0-20 9-20 20z"
                />
              </svg>
            </div>
            <div class="text">Add to cart</div>
          </button>

          <a href="{{ url_for('main.methods_pay', product_id=p.id) }}">
            <button type="button" class="my-Btn">
              <div class="sign">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                  <path
                    d="M13.5 3h-11A2.5 2.5 0 0 0 0 5.5v5A2.5 2.5 0 0 0 2.5 13h11a2.5 2.5 0 0 0 2.5-2.5v-5A2.5 2.5 0 0 0 13.5 3zM3 8H2V6h1v2zm11-1H5V5h9v2z"
                    fill-rule="evenodd"
                  />
                </svg>
              </div>
              <div class="text">Buy now</div>
            </button>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p style="text-align: center; color: red; font-size: medium">
  <i>Không có sản phẩm nào!!!</i>
</p>
{% endif %}

<!-- Pagination -->
{% if pagination and pagination.pages > 1 %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item {% if not pagination.has_prev %} disabled {% endif %}">
      <a
        class="page-link"
        href="{{ url_for('main.home', page=pagination.prev_num) }}"
        hx-get="{{ url_for('main.home', page=pagination.prev_num) }}"
        hx-target="#product-list"
        hx-swap="innerHTML"
        hx-push-url="true"
        >&laquo;</a
      >
    </li>
    {% for page in pagination.iter_pages(left_edge=1, right_edge=1,
    left_current=2, right_current=2) %} {% if page %}
    <li class="page-item {% if page == pagination.page %} action {% endif %}">
      <a
        class="page-link"
        href="{{ url_for('main.home', page=page) }}"
        hx-get="{{ url_for('main.home', page=page) }}"
        hx-target="#product-list"
        hx-swap="innerHTML"
        hx-push-url="true"
        >{{ page }}</a
      >
    </li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">...</span></li>
    {% endif %} {% endfor %}
    <li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
      <a
        class="page-link"
        href="{{ url_for('main.home', page=pagination.next_num) }}"
        hx-get="{{ url_for('main.home', page=pagination.next_num) }}"
        hx-target="#product-list"
        hx-swap="innerHTML"
        hx-push-url="true"
        >&raquo;</a
      >
    </li>
  </ul>
</nav>
{% endif %}

flaskproject/templates/partials/_product_promotion.html
<section id="flash-sale-container" class="flash-sale-section" style="display: none;">

    <div class="flash-sale-header">
        
        <div class="header-left">
            <!-- <h2>🔥 FLASH SALE GIÁ SỐC 🔥</h2> -->
            <img src="{{ url_for('static', filename='img/flashsale.png') }}" alt="fl">
            <p>Sản phẩm kết thúc sau:</p>
        </div>
        
        <div id="countdown-timer" class="header-right">
            <p class="timer-label">Chỉ còn:</p>
            <div class="timer-display">
                <span id="hours">00</span>
                <span class="separator">:</span>
                <span id="minutes">00</span>
                <span class="separator">:</span>
                <span id="seconds">00</span>
            </div>
        </div>
        
    </div> <div id="flash-sale-products-grid" class="products-grid">
        </div>

</section>